### ISSUE TITLE
Problem with GraphCrawl

### ISSUE THREAD

**Issue by SherifWaly** [opencharles/charles#92] opened 2017-04-16 12:22 UTC
``GraphCrawlITCase.crawlsAllPages()`` test fails sometimes with ``WebDriverException`` error

**Comment by amihaiemil** [comment] 2017-04-19 07:11
@SherifWaly Do you want to spend more time here, do some debugging, find out when exactly that "NoSuchElement" occurs? :D I assigned it to me, but I won't have time for this and I would like to know what exactly the problem is

**Comment by SherifWaly** [comment] 2017-04-19 12:47
@amihaiemil Ok, I will debug it to find when the problem occurs exactly :)

**Comment by amihaiemil** [comment] 2017-04-19 12:53
@SherifWaly Thank you :D

**Comment by amihaiemil** [comment] 2017-04-19 19:25
We're going to try an remove phantomjs from IT, in #96

**Closed by amihaiemil** 2017-04-19 19:25 UTC
Labels: 30min, bug, SherifWaly
